apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: smart-taskops
data:
  PORT: "4000"
  NODE_ENV: "production"
  TASK_SERVICE_URL: "http://task-service.smart-taskops.svc.cluster.local:4001"
