apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: smart-taskops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: ghcr.io/oliverphaser/smart-taskops-api-gateway:9427b3e3dd3da7ecdab5a7e971afdee4681cf5d3
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: api-gateway-config
