apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: smart-taskops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/oliverphaser/smart-taskops-frontend:9427b3e3dd3da7ecdab5a7e971afdee4681cf5d3
          ports:
            - containerPort: 80
