apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server
  namespace: smart-taskops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-server
  template:
    metadata:
      labels:
        app: mcp-server
    spec:
      containers:
        - name: mcp-server
          image: ghcr.io/oliverphaser/smart-taskops-mcp-server:9427b3e3dd3da7ecdab5a7e971afdee4681cf5d3
          ports:
            - containerPort: 4100
          envFrom:
            - configMapRef:
                name: mcp-server-config
