apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  namespace: smart-taskops
spec:
  selector:
    app: mcp-server
  ports:
    - port: 4100
      targetPort: 4100
      protocol: TCP
  type: ClusterIP
